### ISSUE TITLE
NameError: name 'GFlux_frac' is not defined

### ISSUE THREAD

**Issue by saeedm31** [SLSkrzypinski/TESS_diagnosis#1]
(base) MacBook-Pro:TESS_diagnosis-master shojjatpanah$ python TESS_diagnosis_main.py 267802440 17
Working on TIC 267802440, sector 17
Downloading and plotting light curve
Creating GLS periodogram
Plotting periodogram
Plotting phased LC
Working on TPF
Working on TIC267802440 (ra = 10.70103953, dec = 35.5487939002615) ...
    --> Target found in the CTL!
    --> Using pipeline aperture...
Traceback (most recent call last):
  File "TESS_diagnosis_main.py", line 36, in <module>
    func.summary_pdf(tic,TESS_sector,best_period,period_error,fap)
  File "/Users/shojjatpanah/Downloads/TESS_diagnosis-master/functions.py", line 128, in summary_pdf
    round(fap,4))+GFlux_frac)
NameError: name 'GFlux_frac' is not defined

**Comment by SLSkrzypinski** [comment]
Thank you for the warning. It should work correctly now (corrected the name GFlux_frac -> Gflux_frac).
